### PR TITLE
Handle `to_date` as `end of the date` in default behavior

### PR DESCRIPTION
**Pull request by kachick**
Sounds useful to me.

### CODE REVIEW

**Comment by kachick** [comment]
I'll resolve the conflict since https://github.com/ohbarye/kpt-bot/pull/13.

**Comment by ohbarye** [comment]
Yeah, that's the behavior most people would expect.
So I was thinking I'd like to use [moment.js](http://momentjs.com/) (it's bundled already) to handle date/time upon working on https://github.com/ohbarye/kpt-bot/issues/9.

**Comment by ohbarye** [comment]
Let me close this because https://github.com/ohbarye/kpt-bot/pull/16 has solved the issue. 🙇 
Thanks for your contribution!

**Comment by kachick** [comment]
🙆‍♂️

**Pull request closed without merging**
